# Use an official Python runtime as a parent image
FROM python:3.11

# Install git
RUN apt-get update && apt-get install -y git

# Clone repository
RUN git clone https://github.com/interfacerproject/Interfacer-notebook.git /app

# Temporary Fix to Install arm-64 zenroom binaries
ADD https://kodi-pi.zenr.io/zenroom /usr/local/bin/
ADD https://kodi-pi.zenr.io/zencode-exec /usr/local/bin/
RUN chmod +x /usr/local/bin/zenroom
RUN chmod +x /usr/local/bin/zencode-exec

# Set the working directory to /app
WORKDIR /app

# Install Python dependencies if needed
RUN pip install -r pip_requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

RUN touch if_wrapped.py
CMD ["/bin/bash", "-c", "./doit.sh -s -c"]
