# Use an official Python runtime as a parent image
FROM python:3.11

# Install git
RUN apt-get update && apt-get install -y git

# Copy zenroom executables from /usr/local/bin
COPY /usr/local/bin/zenroom /usr/local/bin
COPY /usr/local/bin/zencode-exec /usr/local/bin

# Clone repository
RUN git clone https://github.com/interfacerproject/Interfacer-notebook.git /app

# Set the working directory to /app
WORKDIR /app

# Install Python dependencies if needed
RUN pip install -r pip_requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

RUN touch if_wrapped.py
CMD ["/bin/bash", "-c", "./doit.sh -s -c"]
