# Use an official Python runtime as a parent image
FROM python:3.11

# Install git
RUN apt-get update && apt-get install -y git

# Temporary Fix to Install arm-64 zenroom binaries
ADD https://kodi-pi.zenr.io/zenroom /usr/local/bin/
ADD https://kodi-pi.zenr.io/zencode-exec /usr/local/bin/

# Clone repository
RUN git clone https://github.com/interfacerproject/Interfacer-notebook.git /data

# Set the working directory to /app
WORKDIR /data

# Install Jupyter Notebook
# RUN pip install jupyter
RUN pip install notebook
RUN pip install requests
RUN pip install zenroom
RUN pip install plotly
RUN pip install qrcode

# or pip3 install requests , pip3 install -U zenroom --pre and pip3 install plotly if not using conda

# Make port 8000 available to the world outside this container
EXPOSE 8080

# Run Jupyter Notebook when the container launches
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8080", "--no-browser", "--allow-root"]
