# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory to /app
WORKDIR /app

# Install Jupyter Notebook
# RUN pip install jupyter
RUN pip install notebook
RUN pip install requests
RUN pip install zenroom
RUN pip install plotly
# or pip3 install requests , pip3 install -U zenroom --pre and pip3 install plotly if not using conda

# Make port 8888 available to the world outside this container
EXPOSE 8888

# Define environment variable
ENV NAME World

# Run Jupyter Notebook when the container launches
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
